source 'https://github.com/CocoaPods/Specs.git'


target 'ModelAExten_Example' do
  use_frameworks!
  pod 'ModelAExten', :path => '../'

  target 'ModelAExten_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
